<a href="https://colab.research.google.com/github/hsching/Airline-Passenger-Satisfaction-Predictive-Models/blob/main/2_Dataset_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import file from the folder "ISOM3360" in our MyDrive, with shortcut of shared folder "ISOM3360 group project" in
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

Mounted at /content/drive

# mixed standardization + MinMax

In [ ]:
file_name = 'train_processed (mixed).csv'
loc = ''
# loc = '/content/drive/MyDrive/ISOM3360/ISOM3360 group project/Cathy_Data preparation, Decision tree/'
train = pd.read_csv(loc+file_name,index_col=0)
train_df = train.copy()
train_df

,Age,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,...,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus,Flight Distance_binned_long,Flight Distance_binned_middle,Flight Distance_binned_short,satisfaction_satisfied
id,,,,,,,,,,,,,,,,,,,,,
70172,-1.745279,0.6,0.8,0.6,0.2,1.0,0.6,1.0,1.0,0.8,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5047,-0.951360,0.6,0.4,0.6,0.6,0.2,0.6,0.2,0.2,0.2,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
110028,-0.885200,0.4,0.4,0.4,0.4,1.0,1.0,1.0,1.0,0.8,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
24026,-0.951360,0.4,1.0,1.0,1.0,0.4,0.4,0.4,0.4,0.4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
119299,1.430397,0.6,0.6,0.6,0.6,0.8,1.0,1.0,0.6,0.6,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94171,-1.083680,0.4,0.2,0.4,0.6,0.4,0.4,0.4,0.4,0.6,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
73097,0.636478,0.8,0.8,0.8,0.8,0.4,0.8,1.0,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
68825,-0.620561,0.2,0.2,0.2,0.6,0.8,0.2,1.0,0.8,0.6,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
54173,-1.149840,0.2,0.2,0.2,1.0,0.2,0.2,0.2,0.2,0.8,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
62567,-0.819040,0.2,0.6,0.6,0.6,0.2,0.2,0.2,0.2,0.2,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

## Get data ready and split the data

In [ ]:
X = train_df.iloc[:,0:26]  #features
y = train_df['satisfaction_satisfied']  #target label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

## Build the Decision Tree model

In [ ]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# test model
y_pred = model.predict(X_test)

In [ ]:
# evaluate model
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc

print('Accuracy score:', accuracy_score(y_test, y_pred))
print('Classification report:\n', classification_report(y_test, y_pred))
print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))

Accuracy score: 0.945262499398489
Classification report:
               precision    recall  f1-score   support

         0.0       0.95      0.95      0.95     23385
         1.0       0.94      0.94      0.94     18177

    accuracy                           0.95     41562
   macro avg       0.94      0.94      0.94     41562
weighted avg       0.95      0.95      0.95     41562

Confusion matrix:
 [[22200  1185]
 [ 1090 17087]]

# all MinMax

In [ ]:
file_name = 'train_processed (all MinMax).csv'
loc = ''
# loc = '/content/drive/MyDrive/ISOM3360/ISOM3360 group project/Cathy_Data preparation, Decision tree/'
train = pd.read_csv(loc+file_name,index_col=0)
train_df = train.copy()
train_df

,Age,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,...,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus,Flight Distance_binned_long,Flight Distance_binned_middle,Flight Distance_binned_short,satisfaction_satisfied
id,,,,,,,,,,,,,,,,,,,,,
70172,0.076923,0.6,0.8,0.6,0.2,1.0,0.6,1.0,1.0,0.8,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5047,0.230769,0.6,0.4,0.6,0.6,0.2,0.6,0.2,0.2,0.2,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
110028,0.243590,0.4,0.4,0.4,0.4,1.0,1.0,1.0,1.0,0.8,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
24026,0.230769,0.4,1.0,1.0,1.0,0.4,0.4,0.4,0.4,0.4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
119299,0.692308,0.6,0.6,0.6,0.6,0.8,1.0,1.0,0.6,0.6,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94171,0.205128,0.4,0.2,0.4,0.6,0.4,0.4,0.4,0.4,0.6,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
73097,0.538462,0.8,0.8,0.8,0.8,0.4,0.8,1.0,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
68825,0.294872,0.2,0.2,0.2,0.6,0.8,0.2,1.0,0.8,0.6,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
54173,0.192308,0.2,0.2,0.2,1.0,0.2,0.2,0.2,0.2,0.8,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
62567,0.256410,0.2,0.6,0.6,0.6,0.2,0.2,0.2,0.2,0.2,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

## Get data ready and split the data

In [ ]:
X = train_df.iloc[:,0:26]  #features
y = train_df['satisfaction_satisfied']  #target label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

## Build the Decision Tree model

In [ ]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# test model
y_pred = model.predict(X_test)

In [ ]:
# evaluate model
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc

print('Accuracy score:', accuracy_score(y_test, y_pred))
print('Classification report:\n', classification_report(y_test, y_pred))
print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))

Accuracy score: 0.9452865598383139
Classification report:
               precision    recall  f1-score   support

         0.0       0.95      0.95      0.95     23385
         1.0       0.94      0.94      0.94     18177

    accuracy                           0.95     41562
   macro avg       0.94      0.94      0.94     41562
weighted avg       0.95      0.95      0.95     41562

Confusion matrix:
 [[22201  1184]
 [ 1090 17087]]

# all standardization

In [ ]:
file_name = 'train_processed (all standardization).csv'
loc = ''
# loc = '/content/drive/MyDrive/ISOM3360/ISOM3360 group project/Cathy_Data preparation, Decision tree/'
train = pd.read_csv(loc+file_name,index_col=0)
train_df = train.copy()
train_df

,Age,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,...,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus,Flight Distance_binned_long,Flight Distance_binned_middle,Flight Distance_binned_short,satisfaction_satisfied
id,,,,,,,,,,,,,,,,,,,,,
70172,-1.745279,0.203579,0.616172,0.173776,-1.547323,1.352264,-0.185532,1.183099,1.231704,0.479403,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5047,-0.951360,0.203579,-0.695245,0.173776,0.018094,-1.656326,-0.185532,-1.849315,-1.769081,-1.849161,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
110028,-0.885200,-0.549533,-0.695245,-0.541060,-0.764614,1.352264,1.296496,1.183099,1.231704,0.479403,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
24026,-0.951360,-0.549533,1.271880,1.603448,1.583511,-0.904178,-0.926545,-1.091211,-1.018885,-1.072973,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
119299,1.430397,0.203579,-0.039537,0.173776,0.018094,0.600117,1.296496,1.183099,-0.268688,-0.296785,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94171,-1.083680,-0.549533,-1.350954,-0.541060,0.018094,-0.904178,-0.926545,-1.091211,-1.018885,-0.296785,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
73097,0.636478,0.956691,0.616172,0.888612,0.800803,-0.904178,0.555482,1.183099,1.231704,1.255590,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
68825,-0.620561,-1.302646,-1.350954,-1.255895,0.018094,0.600117,-1.667559,1.183099,0.481508,-0.296785,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
54173,-1.149840,-1.302646,-1.350954,-1.255895,1.583511,-1.656326,-1.667559,-1.849315,-1.769081,0.479403,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
62567,-0.819040,-1.302646,-0.039537,0.173776,0.018094,-1.656326,-1.667559,-1.849315,-1.769081,-1.849161,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

## Get data ready and split the data

In [ ]:
X = train_df.iloc[:,0:26]  #features
y = train_df['satisfaction_satisfied']  #target label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

## Build the Decision Tree model

In [ ]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# test model
y_pred = model.predict(X_test)

In [ ]:
# evaluate model
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc

print('Accuracy score:', accuracy_score(y_test, y_pred))
print('Classification report:\n', classification_report(y_test, y_pred))
print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))

Accuracy score: 0.9454549829170877
Classification report:
               precision    recall  f1-score   support

         0.0       0.95      0.95      0.95     23385
         1.0       0.94      0.94      0.94     18177

    accuracy                           0.95     41562
   macro avg       0.94      0.94      0.94     41562
weighted avg       0.95      0.95      0.95     41562

Confusion matrix:
 [[22200  1185]
 [ 1082 17095]]